### ISSUE TITLE
validate-commit-msg crashes when trying to commit

### ISSUE THREAD

**Issue by mramato** [Frikki/validate-commit-message#2]
Originally discussed in https://github.com/karma-runner/karma/pull/1816.

Whenever I try to commit to the karma repository (or rather my fork of it), validate-commit-msg crashes with the following error:

```
C:\Git\mramato\karma\node_modules\validate-commit-msg\index.js:103
      return buffer.toString().split('\n').shift();
                   ^

TypeError: Cannot read property 'toString' of undefined
    at firstLineFromBuffer (C:\Git\mramato\karma\node_modules\validate-commit-msg\index.js:103:20)
    at ReadFileContext.callback (C:\Git\mramato\karma\node_modules\validate-commit-msg\index.js:92:15)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
```

Here are my system specs:
Windows 7 
Node 4.2.x LTS
Git version 2.6.2.windows.1

Let me know if there's any other information you need or anything I can do to help track down the issue.  Thanks.

**Comment by Frikki** [comment]
You’ve got the wrong repo. This is `validate-commit-message`; I think you want this https://github.com/kentcdodds/validate-commit-msg

**Comment by mramato** [comment]
Whoops, sorry about that.  Thanks.
